# Generated by Django 3.0.8 on 2020-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experiance', models.IntegerField(default=1)),
                ('salaray', models.IntegerField(default=100)),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
