# Generated by Django 3.0.8 on 2020-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiance',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
