# Generated by Django 3.0.8 on 2020-08-06 10:01

from django.db import migrations, models


def generate_superuser(apps, schema_editor):
    from django.contrib.auth.models import User

    if (len(User.objects.all()) == 0):
        superuser = User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="admin")

        superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
